var Lang = {
	FR: {
		lst: {
			usr_role: Array("Aucun", "Lecteur", "Constributeur", "Administrateur"),
		},
		lbl: {
			log: "Login",
			mdp: "Mot de passe",
			portail_select: "Sélectionner un portail",
			search: "Recherche",
			no_result: "aucun résultat",
			createdby: "créé par",
			date_intro: "le",
			title: "Titre",
			admin_portail: "Administration des Portails",
			admin_categorie: "Administration des Catégories",
			admin_article: "Administration des Articles",
			admin_user: "Administration des Utilisateurs",
			form_portail: "Portail",
			form_id: "ID",
			form_categorie: "Catégorie",
			form_portail: "Portail",
			form_action: "Actions",
			form_description: "Description",
			form_nb_article: "Nb Articles",
			modif: "Modification de ",
			object_create: "Création",
			now: "aujourd\'hui"
		},
		btn: {
			connect: "Connexion",
			account: "Mon Compte",
			disconnect: "Déconnexion",
			back: "Retour",
			out_portail: "Revenir à l&apos;accueil",
			modify: "Modifier",
			switch_lang: "Switch to English",
			save: "Sauver",
			cancel: "Annuler",
			valide: "Valider",
			delete: "Supprimer",
			add_article: "Ajouter un nouvel article",
			admin_portail: "Gestion des portails",
			add_portail: "Ajouter un nouveau portail",
			del_portail: "Supprimer le portail",
			edit_portail: "Modifier le portail",
			admin_user: "Gestion des utilisateurs",
			add_user: "Ajouter un utilisateur",
			del_user: "Supprimer un utilisateur",
			edit_user: "Modifier un utilisateur",
			admin_categorie: "Gestion des catégories",
			add_categorie: "Ajouter une catégorie",
			del_categorie: "Supprimer une catégorie",
			edit_categorie: "Modifier une catégorie",
		},
		err: {
			bad_id: "identifiants incorrects",
		},
		msg: {
			confirm_leave_portail1: "Vous allez quitter le portail",
			confirm_leave_portail2: "souhaitez-vous continuer sur le portail",
			confirm_delete_object: "Voulez-vous supprimer cet élément ?",
		}
	},
	EN: {
		lst: {
			usr_role: Array("None", "Reader", "Constributor", "Administrator"),
		},
		lbl: {
			log: "Login",
			mdp: "Password",
			portail_select: "Select a portal",
			search: "Search",
			no_result: "no result",
			createdby: "created by",
			date_intro: "the",
			title: "Title",
			admin_portail: "Portals Administration",
			admin_categorie: "Categories Administration",
			admin_article: "Articles Administration",
			admin_user: "Users Administration",
			form_portail: "Portal",
			form_id: "ID",
			form_categorie: "Category",
			form_portail: "Portal",
			form_action: "Actions",
			form_description: "Description",
			form_nb_article: "Nb of articles",
			modif: "Edit ",
			object_create: "Creation",
			now: "today"
		},
		btn: {
			connect: "Connection",
			account: "My Account",
			disconnect: "Disconnection",
			back: "Back",
			out_portail: "Back to Home",
			modify: "Edit",
			switch_lang: "Passer en Français",
			save: "Save",
			cancel: "Cancel",
			valide: "Ok",
			delete: "Delete",
			add_article: "Add a new article",
			admin_portail: "Portail administration",
			add_portail: "Add a new portal",
			del_portail: "Delete the portal",
			edit_portail: "Edit the portal",
			admin_user: "User administration",
			add_user: "Add a new user",
			del_user: "Delete the user",
			edit_user: "Edit the user",
			admin_categorie: "Category administration",
			add_categorie: "Add a new category",
			del_categorie: "Delete the category",
			edit_categorie: "Edit the category",
		},
		err: {
			bad_id: "incorrect identifiers",
		},
		msg: {
			confirm_leave_portail1: "You will leave the portal",
			confirm_leave_portail2: "do you wish to continue in the portal",
			confirm_delete_object: "Do you want to delete this element ?",
		}
	}
}